title: Song Ji Hyun
description: 성장하는 과정을 깊이 즐기는 개발자입니다.
site_title: Portfolio

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: 송지현
blog_url: https://thdwlgus25.github.io/SongJiHyun/
email: 202245024@itc.ac.kr

# absolute or relative
profile_picture: assets/images/photo.jpg

# Google Analytics ID
google_analytics: 